Input ?= InputValue

cameled:
	dotnet run cameled -- $(INPUT)

dotted:
	dotnet run dotted -- $(INPUT)

kebabed:
	dotnet run kebabed -- $(INPUT)

pascaled:
	dotnet run pascaled -- $(INPUT)

snaked:
	dotnet run snaked -- $(INPUT)

trained:
	dotnet run trained -- $(INPUT)

upsnaked:
	dotnet run upsnaked -- $(INPUT)