<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>replace</ToolCommandName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NiceShell.Cli" Version="2026.108.104.11-cli-add-as-root" />
    <PackageReference Include="NiceShell.Logger" Version="2026.108.101.2-cli-copaster.replaceinfolder-using-core-lib" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.CommandLine" />
    <Using Include="NiceShell" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\lib\Copaster.Replace.csproj" />
    <ProjectReference Include="..\..\case\lib\Copaster.Case.csproj" />
  </ItemGroup>

</Project>
