name: Copaster.Copy.Cli NuGet Publish
on:
  push:
    paths:
      - 'copy/cli/**'
      - '.github/workflows/copy-cli-nuget.yml'
  workflow_dispatch:

jobs:
  publish:
    name: Pack & Publish nuget
    runs-on: ubuntu-latest
    steps:
      - uses: astorDev/versy/calver/nuget@main
        with:
          project: copy/cli/Copaster.Copy.Cli
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
